version: '3.8'
services:
  db:
    container_name: products_db
    image: postgres:13.5

    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    
    ports:
      - 5432:5432

    volumes:
      - ./postgres:/var/lib/postgresql/data